# Generated by Django 3.2.9 on 2022-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_file',
            field=models.BinaryField(),
        ),
    ]
