# Generated by Django 3.2.9 on 2022-01-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawpage', '0003_alter_log_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_file',
            field=models.BinaryField(),
        ),
    ]
