# Generated by Django 3.2.9 on 2022-01-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawpage', '0006_log_log_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
