# Generated by Django 3.2.9 on 2022-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawpage', '0007_log_log_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='edges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='nodes',
            field=models.IntegerField(default=0),
        ),
    ]
