# Generated by Django 3.2.9 on 2022-01-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawpage', '0008_auto_20220112_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log_name',
            new_name='name',
        ),
    ]
