# Generated by Django 3.2.9 on 2022-01-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawpage', '0009_rename_log_name_log_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log_image',
            new_name='image',
        ),
    ]
